// Package docsgen generates per-package README.md files from Go doc
// comments (MC-11, model A: fully generated, no marker regions). Each
// README carries the package doc comment plus link-outs to pkg.go.dev (the
// canonical API reference for a public Go module) and to the project wiki
// (narrative/rationale). It never touches the module's own root README.md,
// which is hand-authored.
package docsgen

import (
	"bytes"
	"flag"
	"fmt"
	"go/ast"
	"go/doc"
	"go/parser"
	"go/token"
	"io"
	"io/fs"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"text/template"
)

// Config controls docsgen's generation behavior.
type Config struct {
	// WikiBaseURL is the base URL used for each package's wiki guide
	// link-out. When empty, it is derived from the module path (assumed
	// github.com/<org>/<repo>): https://github.com/<org>/<repo>/wiki.
	WikiBaseURL string

	// Logf, when set, receives one line per documented or skipped
	// package. Skips are logged with a reason.
	Logf func(format string, args ...any)
}

// skipDirs are directory basenames docsgen never descends into: they hold
// non-library code (cmd, examples), unexported/internal code, or test
// fixtures, none of which the discovery rule documents.
var skipDirs = map[string]bool{
	".git":         true,
	"vendor":       true,
	"node_modules": true,
	"cmd":          true,
	"internal":     true,
	"examples":     true,
	"testdata":     true,
}

// readmeTemplate renders the model-A README: doc comment plus reference
// links. It is a named, package-level var so a later addition (MC-23,
// template overrides) can swap it out without touching the rest of the
// generator.
var readmeTemplate = template.Must(template.New("readme.md").Parse(readmeTemplateText))

const readmeTemplateText = `# {{.PkgName}}

{{.Doc}}

## Reference

- API: <{{.APIURL}}>
{{if .WikiURL}}- Guide: [{{.PkgName}} guide]({{.WikiURL}}/{{.PageName}})
{{end}}
<!-- Generated by cmd/docsgen (MC-11). Do not edit; run ` + "`make docs`" + `. -->
`

// readmeData is the template's input.
type readmeData struct {
	PkgName  string
	Doc      string
	APIURL   string
	WikiURL  string
	PageName string
}

// Generate walks root's module and writes a README.md alongside every
// documented package: an importable package (excluding cmd/, internal/,
// examples/, testdata, and the module root itself) with a package doc
// comment and at least one exported identifier. Output is deterministic:
// identical input yields byte-identical output across runs.
func Generate(root string, cfg Config) error {
	logf := cfg.Logf
	if logf == nil {
		logf = func(string, ...any) {}
	}

	modulePath, err := readModulePath(root)
	if err != nil {
		return err
	}
	if cfg.WikiBaseURL == "" {
		cfg.WikiBaseURL = defaultWikiBase(modulePath)
	}

	dirs, err := discoverDirs(root)
	if err != nil {
		return err
	}

	for _, dir := range dirs {
		importPath := toImportPath(modulePath, root, dir)

		pkg, ok, err := loadPackageDoc(dir, importPath)
		if err != nil {
			return fmt.Errorf("docsgen: %s: %w", dir, err)
		}
		if !ok {
			logf("docsgen: skip %s (no package doc or no exported identifiers)", importPath)
			continue
		}

		content, err := render(pkg, importPath, modulePath, cfg)
		if err != nil {
			return fmt.Errorf("docsgen: render %s: %w", importPath, err)
		}

		outPath := filepath.Join(dir, "README.md")
		if err := os.WriteFile(outPath, content, 0o644); err != nil {
			return fmt.Errorf("docsgen: write %s: %w", outPath, err)
		}
		logf("docsgen: wrote %s", outPath)
	}

	return nil
}

// Run is cmd/docsgen's entry point, factored out here so it's covered by
// this package's tests: main() is reduced to a thin call-and-exit wrapper.
// It parses args (as os.Args[1:]) into a Config and calls Generate; verbose
// log lines go to stdout, flag-parse errors to stderr.
func Run(args []string, stdout, stderr io.Writer) error {
	fset := flag.NewFlagSet("docsgen", flag.ContinueOnError)
	fset.SetOutput(stderr)

	root := fset.String("root", ".", "module root to generate READMEs under")
	wiki := fset.String("wiki", "", "override the wiki base URL (defaults to the module's GitHub wiki)")
	verbose := fset.Bool("v", false, "log each documented/skipped package")

	if err := fset.Parse(args); err != nil {
		return err
	}

	cfg := Config{WikiBaseURL: *wiki}
	if *verbose {
		cfg.Logf = func(format string, a ...any) {
			_, _ = fmt.Fprintf(stdout, format+"\n", a...)
		}
	}

	return Generate(*root, cfg)
}

// discoverDirs returns every candidate package directory under root, sorted,
// excluding root itself (its README.md is hand-authored) and every subtree
// rooted at a skipDirs entry or a hidden/underscore-prefixed directory.
func discoverDirs(root string) ([]string, error) {
	var dirs []string

	err := filepath.WalkDir(root, func(path string, d fs.DirEntry, err error) error {
		if err != nil {
			return err
		}
		if !d.IsDir() {
			return nil
		}

		base := filepath.Base(path)
		if path != root && (skipDirs[base] || strings.HasPrefix(base, ".") || strings.HasPrefix(base, "_")) {
			return filepath.SkipDir
		}
		if path == root {
			return nil
		}

		dirs = append(dirs, path)
		return nil
	})
	if err != nil {
		return nil, fmt.Errorf("docsgen: walk %s: %w", root, err)
	}

	sort.Strings(dirs)
	return dirs, nil
}

// readModulePath reads the module directive out of root/go.mod.
func readModulePath(root string) (string, error) {
	data, err := os.ReadFile(filepath.Join(root, "go.mod"))
	if err != nil {
		return "", fmt.Errorf("docsgen: read go.mod: %w", err)
	}

	for _, line := range strings.Split(string(data), "\n") {
		line = strings.TrimSpace(line)
		if after, ok := strings.CutPrefix(line, "module "); ok {
			return strings.TrimSpace(after), nil
		}
	}

	return "", fmt.Errorf("docsgen: no module directive in %s/go.mod", root)
}

// defaultWikiBase derives the wiki base URL from a github.com module path;
// it returns "" for any other module path shape.
func defaultWikiBase(modulePath string) string {
	if strings.HasPrefix(modulePath, "github.com/") {
		return "https://" + modulePath + "/wiki"
	}
	return ""
}

// toImportPath maps a directory under root to its import path.
func toImportPath(modulePath, root, dir string) string {
	rel, err := filepath.Rel(root, dir)
	if err != nil || rel == "." {
		return modulePath
	}
	return modulePath + "/" + filepath.ToSlash(rel)
}

// loadPackageDoc parses dir's non-test .go files and returns its go/doc
// package, plus whether it satisfies the discovery rule (a package doc
// comment and at least one exported identifier). A directory with zero or
// more than one distinct package name (e.g. an unresolved package clause
// split across files) is treated as undocumented rather than erroring.
//
// Files are parsed individually with parser.ParseFile and grouped with
// doc.NewFromFiles rather than parser.ParseDir/doc.New: both are deprecated
// (ast.Package is a deprecated type) in favor of this file-list form.
func loadPackageDoc(dir, importPath string) (*doc.Package, bool, error) {
	entries, err := os.ReadDir(dir)
	if err != nil {
		return nil, false, err
	}

	fset := token.NewFileSet()
	filesByPkgName := map[string][]*ast.File{}

	for _, e := range entries {
		name := e.Name()
		if e.IsDir() || !strings.HasSuffix(name, ".go") || strings.HasSuffix(name, "_test.go") {
			continue
		}

		f, err := parser.ParseFile(fset, filepath.Join(dir, name), nil, parser.ParseComments)
		if err != nil {
			return nil, false, err
		}
		filesByPkgName[f.Name.Name] = append(filesByPkgName[f.Name.Name], f)
	}

	if len(filesByPkgName) != 1 {
		return nil, false, nil
	}

	var files []*ast.File
	for _, fs := range filesByPkgName {
		files = fs
	}

	p, err := doc.NewFromFiles(fset, files, importPath)
	if err != nil {
		return nil, false, err
	}
	if p.Doc == "" {
		return nil, false, nil
	}
	if exportedCount(p) == 0 {
		return nil, false, nil
	}

	return p, true, nil
}

// exportedCount counts a package's top-level exported identifiers: funcs,
// types (plus their associated funcs and methods), vars, and consts.
func exportedCount(p *doc.Package) int {
	n := len(p.Funcs) + len(p.Types) + len(p.Vars) + len(p.Consts)
	for _, t := range p.Types {
		n += len(t.Funcs) + len(t.Methods)
	}
	return n
}

// render executes readmeTemplate for a documented package.
func render(p *doc.Package, importPath, modulePath string, cfg Config) ([]byte, error) {
	data := readmeData{
		PkgName:  p.Name,
		Doc:      strings.TrimSpace(p.Doc),
		APIURL:   "https://pkg.go.dev/" + importPath,
		WikiURL:  cfg.WikiBaseURL,
		PageName: pageName(importPath, modulePath),
	}

	var buf bytes.Buffer
	if err := readmeTemplate.Execute(&buf, data); err != nil {
		return nil, err
	}
	return buf.Bytes(), nil
}

// pageName derives a stable wiki page name from a package's import path,
// relative to the module: each path segment is title-cased and joined with
// "-" (e.g. "host/generic" -> "Host-Generic"). It is a pure function of its
// inputs.
func pageName(importPath, modulePath string) string {
	rel := strings.TrimPrefix(importPath, modulePath)
	rel = strings.TrimPrefix(rel, "/")
	if rel == "" {
		rel = filepath.Base(modulePath)
	}

	segs := strings.Split(rel, "/")
	for i, s := range segs {
		if s == "" {
			continue
		}
		segs[i] = strings.ToUpper(s[:1]) + s[1:]
	}
	return strings.Join(segs, "-")
}
